[frontend.my-rest]
type = "http-rest"
url = "https://foo.bar/baz?qux=corge"
#basic_auth = { username = "", password = "" }
frequency_secs = 10

[frontend.my-mqtt]
type = "mqtt"
host = "localhost"
#port = 1883
#username = ""
#password = ""

[backend.my-postgres]
type = "postgres"
host = "localhost"
#port = 5432
database = "telemetry"
username = "telemetry"
#password = ""

[data.ahoydtu]
frontend.name = "my-rest"
frontend.data_type = "wide"
backend.name = "my-postgres"
backend.postgres_table = "ahoydtu"
# persistence / non-persistence requires a "timestamp" column and a "persistent" bool column
#persistent_every_secs = 120
#clean_non_persistent_after_days = 14
# preprocess before backend-escaping, postprocess after backend-escaping
values.timestamp = { pointer = "/inverter/0/ts_last_success", postprocess = 'f"to_timestamp({value})"' }
values.ac_voltage = { pointer = "/inverter/0/ch/0/0" }
values.ac_current = "/inverter/0/ch/0/1"

[data.tasmota]
frontend.name = "my-mqtt"
frontend.data_type = "wide"
frontend.mqtt_topic = "tele/tasmota/SENSOR"
backend.name = "my-postgres"
backend.postgres_table = "foo"
values.power = "/tele~1tasmota~1SENSOR/ENERGY/Power"
